# Generated by Django 4.2.7 on 2023-11-22 12:31

from django.db import migrations, models
import quotes.models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('path', models.ImageField(upload_to=quotes.models.update_filename, validators=[quotes.models.validate_file_size])),
            ],
        ),
    ]
